name: recipe_ai_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_ai: ^3.6.1
  google_generative_ai: ^0.4.7
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Asset declaration for 'config.env'
  assets:
    - assets/config.env
    - images/