name: recipe_ai_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^2.20.0
  firebase_auth: ^4.8.0
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/config.env
    - assets/google_logo.png
